### ISSUE TITLE
Disable the service when no network is available

### ISSUE THREAD

**Issue by ghost** [ygini/Hello-IT#11]
During my tests I noticed a tiny problem. We've a large majority of laptops and when users disconnect their equipment and no network is available, all services are shown as red.

But when the network is unavailable it's not meaning that everything is down.

It will be great if the app can detect when the network is down and show any information that the services can't be checked for the moment with a grey status (example) because the network is unavailable.

**Comment by ygini** [comment]
This feature has been implemented in release 1.0.1
