### ISSUE TITLE
Unable to change icons

### ISSUE THREAD

**Issue by AndersTao** [ygini/Hello-IT#13]
I am unable to get the app to read new icons from another folder
Here is my test plist [gist](https://gist.github.com/AndersTao/8f7b8aeeed5545a16eed0feecde90223)
For testing, I just copied the icons from the repo, and modified them just enough to to see if icon changed

Don't know if related,this message is found in the console no matter where I place the plist, even using the sample from the wiki.

> Hello IT[41835]: No settings found in com.github.ygini.Hello-IT domain. Loading sample one.

Testet with 10.11.4 and Hello-IT 1.1.1

**Comment by ygini** [comment]
Hi

Indeed the error means your plist isn't found by the app.

Since you're working with plist file, did you correctly followed this documentation: https://github.com/ygini/Hello-IT/wiki/Preferences ? 

```
killall cfprefsd
```

**Comment by AndersTao** [comment]
It looks like the plist is read by the app, if I update the "Apple" title to "Apple2", it is reflected when i kill, and re-launch Hello-IT.

When not testing, I normally use a configuration profile, and I see the same error in the console

Did I added the keys correctly to my plist? I am unsure about the pleacement of the key's
