### ISSUE TITLE
Add images/icons next to Resources

### ISSUE THREAD

**Issue by jbaker10** [ygini/Hello-IT#14]
This is a feature request to have the ability to add icons or images next to defined resources. This would be very nice when adding URL's that customers can click, and being able to add an icon next to the URL, such as the status indicator for services.

Ideally this would be another `<key>` you could define within the `<settings>` dict. So it would look something like:

```
<dict>
    <settings>
    <dict>
        <key>URL</key>
        <string>https://resource.com</string>
        <key>title</key>
        <string>Resource Name</string>
        <key>image</key>
        <string>Resource.png</string>
    </dict>
</dict>
```

The resources could be kept in a location under `/Library/Application Support/`perhaps?

Thanks for the great work on the product!

**Comment by ygini** [comment]
Implemented in 1.2
