### ISSUE TITLE
French version of "quit" item

### ISSUE THREAD

**Issue by Darkomen78** [ygini/Hello-IT#15]
Add "Quitter" for the french version of the "public.quit".

**Comment by ygini** [comment]
The default implementation for public.quit has a translation table that need to be completed.

If you've time, you can open the Quit plugin project and localized the translation string file

https://github.com/ygini/Hello-IT/blob/master/src/Plugins/Quit/Quit/Localizable.strings

**Comment by Darkomen78** [comment]
Already done
