### ISSUE TITLE
Refreshing of data

### ISSUE THREAD

**Issue by franton** [ygini/Hello-IT#16]
Currently the menu bar app is only showing data captured by scripts and functions upon first run of the application. Are there any plans to implement periodic refreshing of the data?

**Comment by ygini** [comment]
This is a good idea. I will look to add automatic refresh when new settings are loaded from profile.

I will also add support for kill HUP signal.

**Comment by franton** [comment]
I meant periodic re-running of the scripts that gather the data. So if IP address changes, that information will update.

**Comment by ygini** [comment]
This is already supported, scripted items and network check functions does have a periodicity settings. 

In both case it's the "repeat" key in settings dict who must be used to specify the interval in seconds between each run.

**Comment by franton** [comment]
Yep i'm wrong!
