### ISSUE TITLE
Fast User Switching

### ISSUE THREAD

**Issue by franton** [ygini/Hello-IT#17]
The standard launch agent is fine for launching Hello-IT on login. However if it is already running and you switch back and forth between user accounts, Hello-IT can load multiple times.

I am not sure if modifications to the LaunchAgent or the binary would be most suitable for this edge case.

**Comment by ygini** [comment]
I'm not sure to understand. 

If you switch between account with Fast User Switching, you will have one instance of Hello IT per user, this is normal, since different user may have different Hello IT settings (IT guys may have more advanced script test for example).

**Comment by franton** [comment]
I was able to get two instances of Hello-IT running in the same user space by simply fast user switching to another account and back.

**Comment by ygini** [comment]
It don't act like that on my computer. Are you able to reproduce the bug all the time? Even after a reboot?

**Comment by franton** [comment]
Ugh, it's not happening consistently here either. Best way of replicating is to fast user switch to another account, then fast user switch (without logging out) back to the original.

**Comment by ygini** [comment]
I've tried again and I can't reproduce it. Do you've to wait when you're on the other session to make this happen?

Are you at PSU this week?

**Comment by franton** [comment]
Ugh. I replicated this exactly twice out of five times. I'm going to assume this is due to something i've done.

**Comment by ygini** [comment]
Have you been able to replicate the problem on a new computer?
