### ISSUE TITLE
Broken HTTP Test?

### ISSUE THREAD

**Issue by rickychilcott** [ygini/Hello-IT#21]
I have some broken HTTP Test's in the latest version of Hello IT. My config file is here:

https://github.com/OhioUniversityScripps/scripps_college_scripts/blob/a005e816885a505f4424bdc49aded63be5587886/edu.ohio.scripps.HelloIT-Settings/payload/Library/Preferences/com.github.ygini.Hello-IT.plist

Version 1.2.1 works OK with the same settings, but the HTTP test is broken in  Version 1.2.6

Screenshot of Version 1.2.1
<img width="342" alt="version1 2 1" src="https://cloud.githubusercontent.com/assets/445759/19115375/b5750366-8adf-11e6-829a-3151b2a5045c.png">

Screenshot of Version 1.2.6
<img width="342" alt="version1 2 6" src="https://cloud.githubusercontent.com/assets/445759/19115418/e77042e0-8adf-11e6-8c8a-bdc1e76a8452.png">

Can you try to reproduce or let me know if there is a problem with our config file? I'm not seeing any changes in the wiki that would indicate a change. Thank you @ygini!

/cc @andyvanfossen @pettitr

**Comment by rickychilcott** [comment]
Thanks @ygini can you share how/why this commit fixes it? I don't have much experience with Xcode or Mac OS Dev, but I'd love to understand. Thanks again!

**Comment by ygini** [comment]
Well, this commit and bug isn't the most interesting to start any interest in OS X dev.

The Reachability framework is a poor sample code provided by Apple with not that much documentation. My previous code was using the Apple sample and nothing more. I've improved the situation by using an other implementation.

**Comment by rickychilcott** [comment]
Thanks for the info and for providing a great tool

**Comment by grahampugh** [comment]
Hi, I still can't get this to work. The icon only turns to "OK" when I switch to thunderbolt internet, and then after around a minute it returns to the undetermined icon. I haven't set a timeout.  

In the meantime I have to effectively disable this function by setting the "OK" icon to be the same as the "undetermined" one, since the information provided is not meaningful.

**Comment by ygini** [comment]
@grahampugh the undetermined icon is here when your system tell to Hello IT that Internet isn't available.

Does your Internet is filtered?

Can you share your current config with real URLs used to test the Internet? (if you can't disclose publicly your URLs, send me a private message)

Which Hello IT version are you using? On which macOS version?

**Comment by grahampugh** [comment]
Yes, we use proxy PAC files. I would not be surprised if that was the issue. I'm not sure how to test it though.
I'm using the latest version of Hello IT on the latest version of macOS.
Nothing special about our URL check. The URL always appears to work in a browser, but we may well need to set a proxy for this test somehow as shell scripts do not use system proxy settings:

``` xml
        <!-- Check network state -->
            <dict>
                <key>functionIdentifier</key>
                <string>public.test.http</string>
                <key>settings</key>
                <dict>
                    <key>URL</key>
                    <string>http://captive.apple.com/hotspot-detect.html</string>
                    <key>mode</key>
                    <string>md5</string>
                    <key>originalString</key>
                    <string>73a78ff5bd7e5e88aa445826d4d6eecb</string>
                    <key>repeat</key>
                    <integer>60</integer>
                    <key>title</key>
                    <string>Network Status</string>
                    <key>imageBaseName</key>
                    <string>network</string>
                </dict>
            </dict>
            <!-- End of Check network state -->
```

**Comment by ygini** [comment]
When Hello IT turn gray again, if you try to open a page via Safari, do you see a proxy page or redirect?

If the status turn gray, this mean captive.apple.com (hardcoded value for global Internet access in the app, not related to your settings) is seen as unavailable by the system itself.

Also look at logs, I've added many logs function to help people to trace errors in this case.

**Comment by ygini** [comment]
Hi folks

This release introduction a workaround option to use when something on your network cause issue with network state reported by the system

https://github.com/ygini/Hello-IT/releases/tag/v1.2.8
