### ISSUE TITLE
Running generic bash/python scripts from Hello IT?

### ISSUE THREAD

**Issue by grahampugh** [ygini/Hello-IT#22]
Hi,
Is it possible to embed generic scripts in the CustomScripts folder and run them from a menu item?
If so, would these run as the logged in user or as root?
I'm thinking tools like resetting network settings or running a reconnection to your management server could be useful.

**Comment by ygini** [comment]
Hello IT is a process usually started by the login window as a LoginAgent, so with the user rights.

The app has built-in modules who are Cocoa Plugins using a open API to add feature to Hello IT.

The app alone can't to anything at all. Everything is provided by functions. The apps come with few functions useful to all (IMHO) and one of this function is a script extension.

https://github.com/ygini/Hello-IT/wiki/public.script.item

The goal of this function is not just to run a script but to allow you to create your own extension without having to write Cocoa Plugins.

The script can be any kind of executable on the Mac who can handle args and stdout. You've to use specific print on the stdout to interact with Hello IT main app according to the args.

Your script can be run multiple time according to the function configuration (in the Hello IT config file) with a verb as first argument. This verb will tells you when your script is requested for the item title (first boot), for a user clic, or for a periodic run. 

This script will be started with Hello IT rights.

So for you, I will recommend to write a script according to the documentation, and in case of a run request, run an other script with sudo. And in your deployment package should install a file in /etc/sudoers.d to allow %staff to run it without password. (please be careful to your files permissions to not open a security breach).

The other option would be to write a custom plugin using the security mechanism built in macOS to run a privileged helper tool. More complicated, but more secure and clean.

**Comment by ygini** [comment]
@grahampugh have you been able to solve your issue?
