### ISSUE TITLE
Hello-IT subdomains only function in Home dir

### ISSUE THREAD

**Issue by WardsParadox** [ygini/Hello-IT#23]
Issue:
Using the new additional domains ie: (com.github.ygini.Hello-IT.000IT.plist, etc) does not work in the `/Library/Preferences/` directory. It does work perfectly in `~/Library/Preferences/`.

Example:
Close Hello-IT
Copy two example plists from the example directory to `/Library/Preferences`
Open Hello-IT. Hello-IT will only load `com.github.ygini.Hello-IT.plist` in the `/Library/Preferences` and will ignore the 000IT.plist file.

Repeat except for `~/Library/Preferences` and Hello-IT obeys new files.

**Comment by WardsParadox** [comment]
I will test via MobileConfig method as well and report.

**Comment by ygini** [comment]
Indeed, at this time subdomain seems to work only in user domain. Deploying preferences with mobileconfig don't change anything. I will find a way…

**Comment by ygini** [comment]
For now I will have to restrict this feature to user level preferences until I found a way to properly discover system level preferences

Current doc here https://github.com/ygini/Hello-IT/wiki/Preferences-subdomain

**Comment by ygini** [comment]
This issue will not be fixed. I didn't found a clean way to list all domains from all kind of management sources.

Consider subdomains as an option for admins to test new menu organization.
