### ISSUE TITLE
Not proxy aware

### ISSUE THREAD

**Issue by franton** [ygini/Hello-IT#30]
Hello.

I work in an environment where all network traffic for the internet has to go through our authenticated proxy servers. Hello IT's internet connection check doesn't seem to use any configured proxy addresses.

As part of the configuration I do, I'm using networksetup to set both http and https proxies with no user/pass auth because it's all authenticated via kerberos. I'm similarly setting environment variables "http_proxy" "https_proxy" "HTTP_PROXY" "HTTPS_PROXY" to the same address.

Can this be implemented?

**Comment by clburlison** [comment]
That's weird. The Test HTTP Plugin is using the Apple's NSURLConnection which should be proxy aware.

https://github.com/ygini/Hello-IT/blob/d38407d24131e4c1aa67f4ce592449f627828ff0/src/Plugins/TestHTTP/TestHTTP/HITPTestHTTP.m#L101

**Comment by franton** [comment]
Wondering if the proxy auth is failing because for some reason it's not automatically using the kerberos ticket?

**Comment by franton** [comment]
To clarify, using the HTTP test to capture.apple.com via a browser does work.

**Comment by ygini** [comment]
That's unexpected… Like @clburlison said, the HTTP test is implemented using NSURLConnection, so proxy should be handled by Apple's SDK…

I will look at it, but @franton could you look for logs related to the HTTP test module and publish here what you got? I need to understand where it fail.

**Comment by franton** [comment]
Will do. That'll be Monday when I get back to the office. I'm having weirdness with other things like the softwareupdate command too. Could be tied to authentication issues to our proxy.

**Comment by franton** [comment]
Ok, so back in the office. Ran this and got this:

rich$ softwareupdate -l
Software Update Tool

Finding available software
The operation couldn’t be completed. (NSURLErrorDomain error -1012.)

Going to assume it's tied to the same issue. Also found that the test proxy I'm having to use does not behave the same as the production system (!). I'll close this for now as I don't see what can be done until I'm on the production system.

**Comment by ygini** [comment]
Indeed, something looks wrong with your proxy setup. Thanks for your feedback

**Comment by franton** [comment]
Ok so I figured out why the http test wasn't working. The MD5 hash on captive.apple.com has changed since your documentation was written. It's now 41ba060eb1c0898e0a4a0cca36a8ca91 .
