### ISSUE TITLE
HIT Text in menu item does not switch to white on dark mode

### ISSUE THREAD

**Issue by WardsParadox** [ygini/Hello-IT#31]
<img width="212" alt="screen shot 2017-05-15 at 8 08 10 am" src="https://cloud.githubusercontent.com/assets/8117192/26072479/e0dc4018-3968-11e7-8c6f-7827b20ff3cc.png">

Using text mode for the menu does work well on dark mode. Default no-issue text should be white not black.

**Comment by ygini** [comment]
Should be fixed in 1.2.11
