### ISSUE TITLE
Feature request: Show more items when holding down option key

### ISSUE THREAD

**Issue by erikng** [ygini/Hello-IT#33]
Like the wifi menu bar item, when you hold down option, you see advanced details. We would like to do this so our helpdesk can quickly look up things but hide them from normal users.

**Comment by ygini** [comment]
It was already in my mind, thanks for pushing this option in the as item 0 on my todolist :)

**Comment by ygini** [comment]
Feature is implemented and will be supported by Hello IT 1.4.0
