### ISSUE TITLE
Potential bug: public.script.item does not honor network setting.

### ISSUE THREAD

**Issue by erikng** [ygini/Hello-IT#34]
I am trying to enforce that a script re-runs when the network state changes, but in my testing it is not honored.

Given that some "boolean" values in HelloIT are actual strings, I tried two different setting configurations:

```
<key>network</key>
<true/>
```

```
<key>network</key>
<string>YES</string>
```

How I am testing this:

1. run HelloIT - configure script with a run of every 10 seconds.
2. Disable my network connection and immediately check menu items. state has not updated
3. Wait 10 seconds - menu state has changed.

**Comment by ygini** [comment]
This bug has been identified and fixed. The fix will be available in the next release: Hello IT 1.4.0

Please, be aware that v1.4.0 will change the script syntax (to remove base64 support and change the way network events are sent to the scripts).

**Comment by erikng** [comment]
what is the proper way to test this? Is the key a true boolean or a string with `YES`?

**Comment by erikng** [comment]
Nevermind - it's a true boolean. Working as intended 👍
