### ISSUE TITLE
Potential bug: retina icons not working

### ISSUE THREAD

**Issue by erikng** [ygini/Hello-IT#35]
In our testing, when using custom icons, the retina version is not being honored.

If as a test we replace one of the 1x pngs, on a retina screen it will instantly change to retina, but on non-retina screens the icon will be rendered at full image size.

My icons are as follows:
20px @72 DPI for 1x
40px @144 DPI for 2x

I opted for 2px more than the recommended 18px, but I don't think this is the issue.

**Comment by ygini** [comment]
Next release will fix this behaviour by moving to the multi resolution tiff file format.

Wiki is already updated so you can prepare: https://github.com/ygini/Hello-IT/wiki/Application-Description#custom-status-bar-icon
