### ISSUE TITLE
Preference Subdomain broken in 1.4.0 beta1

### ISSUE THREAD

**Issue by erikng** [ygini/Hello-IT#36]
It appears as the preference subdomain isn't working on 1.4.0 beta1.

https://github.com/ygini/Hello-IT/wiki/Preferences-subdomain

In my testing, if I downgrade to 1.3.2, my test subdomain works and upgrading back to 1.4.0b1 causes it to not appear.

**Comment by ygini** [comment]
Did you see https://github.com/ygini/Hello-IT/wiki/Security ?

**Comment by erikng** [comment]
Nope! let me test.

**Comment by erikng** [comment]
This fixed it for me. I added some notes on the wiki to clarify this.

https://github.com/ygini/Hello-IT/wiki/Preferences-subdomain

I also updated the readme on the cpe_helloit cookbook to clarify this as well.
