### ISSUE TITLE
suggestion: add killall to postinstall

### ISSUE THREAD

**Issue by erikng** [ygini/Hello-IT#37]
In my testing of Hello-IT upgrades, I've noticed that if the launchagent is already active, Hello-IT won't be upgraded until the next logout/reboot. This is due to the in-memory upgrade and is problematic if you want to use the new `optionalDisplay` feature.

To get around this, I simply added a `/usr/bin/killall "Hello IT"` to the postinstall script. The LaunchAgent will just reload the menubar, and it will be running with the expected version.

Given that the postinstall always exits 0 currently, this shouldn't cause any package install failures on new installs.

**Comment by ygini** [comment]
How did you deployed the app? Which macOS version? 

At this time, the postinstall script is supposed to unload and reload all single instance of the LaunchAgent (in case of a launchd.plist update).

**Comment by ygini** [comment]
@erikng any news on this?

**Comment by erikng** [comment]
I think my issue was related to the fact that I use a custom identifier for my launchagent. Going to close.
