### ISSUE TITLE
Quit Functionality in Custom Scripts 

### ISSUE THREAD

**Issue by dev-yeet** [ygini/Hello-IT#42]
# Setup info

Hello-IT version: 1.4.0
macOS version: 10.13.6 and 10.14(beta at time of writing this)
Preferences deployed via: dropped plist 
Preferences targeting: device

# Setup goal - 

allow quit functionality in user script. By default hello IT is loaded by a LaunchDaemon, so I've used a script to unload it for users. This part works fine, but I am trying to find a way to reload the launch daemon and quit the CURRENT session of Hello IT. Reloading the LD will open a new instance of HIT but ignore the one used to reload.

**Comment by erikng** [comment]
HelloIT should be a LaunchAgent and not a daemon.

Thanks,
Erik Gomez
________________________________

**Comment by ygini** [comment]
Hi folks,

Sorry I'm a bit late on this.

Could you explain more this issue, HIT is launched as LaunchAgents and not LaunchDaemons.

What's your need on this?
