### ISSUE TITLE
Computed text in menubar

### ISSUE THREAD

**Issue by agerson** [ygini/Hello-IT#43]
Can the title of the top level menubar item, the one with the "IT" icon, not the submenu items themselves, be set with a custom script? I would like instead of or in addition to an icon in the menu bar some custom text.

**Comment by ygini** [comment]
Hello,

Sorry for the late answer, no at this time HIT title can't be set by script and I'm not sure if it should be done. In term of User Experience it's better to have a consistent UI…

What's your goal behind?

**Comment by agerson** [comment]
We wanted to include the currently logged in username in the menu title. We are a school in a multi-user environment. It's helpful for the teachers and administrators to see who is currently logged in in an obvious way. I was able to accomplish it by editing the source code directly. I know you can do this with "Fast User Switching", but in a multi-user environment, this becomes very problematic.

**Comment by ygini** [comment]
Why not relying on the native macOS feature? You can set Fast User Switching to display full name on the menu bar for you.

If you improved HIT on this, feel free to send a PR

**Comment by blarwick** [comment]
I’d like to see a text option as well.  Specifically, I’ve been looking for about 4 years now for a way to put the computer’s Sharing Name in the menu bar.

**Comment by ygini** [comment]
Implemented in 1.6.0
