### ISSUE TITLE
Hello-It crashing in Mojave

### ISSUE THREAD

**Issue by mm-johnpeterson** [ygini/Hello-IT#47]
# Setup info

Hello-IT version: 1.4.2
macOS version: 10.14.*
Preferences deployed via: /Users/*/Library/Preferences/com.github.ygini.hello-it.plist
Preferences targeting: user

Please, describe what you were trying to achieve when you got this issue.
From what I can tell when this happens in my machine the app simply relaunches. There is a  prevalence of this in our users logs as it has occurred around the time system hangs happen so I wanted to make you aware of this issue as it presents in only Mojave machines. 
 
# Issue description
I have been trying to isolate full system lock ups on users running 10.14.1 , 10.14.2, 10.14.3 and noticed the attached crash logs in every users Library. I don't believe these crash logs are the source of the system hangs but they are present in every Mojave machine we have.

Please, explain with technical details your issue.
The error is the same in 99% of cases with the only difference being the specific thread that caused the issue. 
Crashed Thread:        8

```
Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [1025]
```

# Related logs
Attached is a sample crash log from ~/Library/Logs/DiagnosticReports/

[Hello IT_2019-03-13-102742_johndoe-mbp.crash.zip](https://github.com/ygini/Hello-IT/files/2962641/Hello.IT_2019-03-13-102742_johndoe-mbp.crash.zip)

**Comment by fulltimecasual** [comment]
Seeing this too

**Comment by ygini** [comment]
Please, could you share with me the content of `~/.CFUserTextEncoding` on your user and tell me which macOS locale are you using?

**Comment by mm-johnpeterson** [comment]
~/.CFUserTextEncoding -- 0x0:0x0

Not positive what you mean by locale. 
My best guess is location, United States, or local System version macOS 10.14.4 (18E226).
If it is the system version that is varied among machines I am seeing this.

**Comment by ygini** [comment]
This pre-release should fix this issue, could you please test and confirm?

https://github.com/ygini/Hello-IT/releases/tag/v1.4.3-beta1

**Comment by mm-johnpeterson** [comment]
I installed the pre-release yesterday and will monitor. I will let you know early next week how it goes. Thanks for putting that together.
