### ISSUE TITLE
Feature Request: HIDPI Status Icons

### ISSUE THREAD

**Issue by pfdan** [ygini/Hello-IT#53]
# Setup info

Hello-IT version: 1.4.4
macOS version: 10.15
Preferences deployed via: dropped plist
Preferences targeting: device

# Issue description

Status icons next to items are slightly fuzzy on HIDPI screens

# Requested solution

Be able to replace these three icons, or update them to have a higher resolution.

**Comment by ygini** [comment]
@WardsParadox could you help on this?

**Comment by WardsParadox** [comment]
I'll see what I can do. I am not sure if I still have the originals or the time until this weekend. I have a couple artists I could reach out to and commission a new icon if you'd like? Make it look a little more professional?

**Comment by pfdan** [comment]
I'm sure we can schedule some time in our design studio, would that be helpful?

**Comment by pfdan** [comment]
Just had a crack at it myself, resolves the issue of them being blurry, but just made them all circles to make it a bit more uniform. Let me know what you think.

![Error tiff](https://user-images.githubusercontent.com/49640335/198271308-12fe9b51-2776-4143-b44c-41531b4528e5.png)
![OK tiff](https://user-images.githubusercontent.com/49640335/198271314-11b9eecf-755f-4332-b86c-a1d3bf813d23.png)
![Unavailable tiff](https://user-images.githubusercontent.com/49640335/198271317-8d96d023-7150-4507-8896-6e4568923156.png)
![Warning tiff](https://user-images.githubusercontent.com/49640335/198271318-9d02943b-4faa-43fa-a881-c03600235034.png)

In .tiff format, for Hello IT
[Icons.zip](https://github.com/ygini/Hello-IT/files/9878816/Icons.zip)


Quick demo:

<img width="469" alt="HIT" src="https://user-images.githubusercontent.com/49640335/198272513-8ca5a764-118f-49ad-af7c-8def3af3d44e.png">

**Comment by WardsParadox** [comment]
LGTM. I don't have the originals anymore unfortunately.

**Comment by RobertArndtEllerhold** [comment]
The circles look very good and I would love to see them included in the next version!

**Comment by pfdan** [comment]
I've opened a pull request https://github.com/ygini/Hello-IT/pull/66
