### ISSUE TITLE
1.4.3 - 1.4.4 Pinwheeling on click 10.15

### ISSUE THREAD

**Issue by firetoole** [ygini/Hello-IT#54]
# Setup info

Hello-IT version: 1.4.4 and 1.4.3
macOS version: 10.14.6 and 10.15
Preferences deployed via: Chef managed profile
Preferences targeting: user - device

# Setup goal
Deployed widely with custom sh scripts for various user interaction or info.

# Issue description
On click of the menubar icon you will get a pinwheel and it will take over mouse focus.
The process will stop responding and stay in a crashed state.
killing the process will spawn a new one and will be back in a working state unless clicked on again.

# Related logs
[hello.tar.gz](https://github.com/ygini/Hello-IT/files/3735859/hello.tar.gz)

**Comment by ygini** [comment]
Hello,

Do you’ve custom script in your deployment?

**Comment by firetoole** [comment]
Yes we have a few, I can share them privately if need be.

**Comment by ygini** [comment]
Yes, I would like to check the content to be sure it does not have any impact. You can do it privately on the MacAdmins’ Slack.

**Comment by ygini** [comment]
Hi

Could you explain briefly what was the cause of this issue and if you've a way to reproduce it? If a buggy script lead to a hang in Hello IT, I should be able to at least protect the general application from this.
