### ISSUE TITLE
Hello IT Freezes

### ISSUE THREAD

**Issue by kingslek** [ygini/Hello-IT#56]
[Sample of Hello IT.txt](https://github.com/ygini/Hello-IT/files/3972581/Sample.of.Hello.IT.txt)

macOS version: Mojave
Preferences deployed via: Configuration Profile - MCX - defaults - dropped plist
Preferences targeting: user - device

# Setup goal

Normal Mac use

# Issue description

Randomly freezes

# Related logs

Attached Sample

# Requested solution
Bug fix

**Comment by ygini** [comment]
This look like to be an issue with your AD being unresponsive when you use the AD plugin.

**Comment by jordigg** [comment]
This also happens with the internet check. The app will get blocked during the check, specially if there is no internet connection available. I think I've seen the same on other checks/scripts with might be long or heavy to execute.
The device itself seems not affected by this but the app will show the spinning wheel if you interact with it.
I'm not very familiar with Swift programming but is there any way to execute the scripts/checks as a child process that doesn't block the parent?

**Comment by jordigg** [comment]
I want to comment that I din't encounter any more freezes during script execution like connectivity check using the latest "beta" release.
