### ISSUE TITLE
Menu Item Title Text Remains Black When Highlighted

### ISSUE THREAD

**Issue by seansgm** [ygini/Hello-IT#57]
# Setup info

Hello-IT version: 1.4.4
macOS version: 10.15.4 beta
Preferences deployed via: Configuration Profile
Preferences targeting: device

# Setup goal

Setting Title Text for the Menu Item.

# Issue description

In Light Mode the text defaults to black, however when highlighting the menu bar it remains black, rather than reversing to white, which can be hard to read on the blue background

**Comment by ygini** [comment]
Should be solved in 1.6.0
