### ISSUE TITLE
Feature Request: Notifications without a State Change

### ISSUE THREAD

**Issue by alexionescu** [ygini/Hello-IT#59]
Hello IT currently supports notifications upon a state change, however for certain scripts it may be helpful to have a way to output to the user via a notification that a command or action was completed successfully, by the script. This feature request is for Hello-IT to allow the execution of a script to display a notification to the user with custom text.

**Comment by ygini** [comment]
Hello

This is already supported by custom scripts.

General feature information is available here https://github.com/ygini/Hello-IT/wiki/public.script.item#supported-commands

And if you are relying on the built-in bash lib, you can use function described here https://github.com/ygini/Hello-IT/wiki/public.script.item#interact-with-hello-it

**Comment by alexionescu** [comment]
Cool, thanks! This must have slipped while I was looking at the docs.
