### ISSUE TITLE
Ability to use an icon instead of text in the menu bar

### ISSUE THREAD

**Issue by homebysix** [ygini/Hello-IT#6]
The ability to use a custom icon in the menu bar would be pretty cool!

Something like this:
<img width="310" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7801391/8752982/cbad723a-2c6c-11e5-985b-7a38ba5de90c.png">

**Comment by ygini** [comment]
I can implement this feature if some can provide a default icon for Hello IT free of rights.

**Comment by WardsParadox** [comment]
Any idea of what style icon?

**Comment by ygini** [comment]
I'm not a really good UI guy, so I won't be able to be really specific. But I think I can say at least:
- in the current OS X style (so black and flatten);
- not close to current well known applications used by everyone;
- using a symbolic understandable by all or almost all nationalities;
- something simple to describe for the poor help desk guy who will lead the end user to click on it to get its IP address.

**Comment by brightghost** [comment]
Something like this? Maybe someone knows another utility this conflicts with?
![screen shot 2015-07-17 at 5 53 23 pm](https://cloud.githubusercontent.com/assets/3108171/8758703/c88c9f0a-2cac-11e5-8c9f-805badab9f1e.png)

**Comment by WardsParadox** [comment]
![helloit](https://cloud.githubusercontent.com/assets/8117192/8758887/4ac67f8c-2ca7-11e5-86c3-8c0941ab23fe.png)
A work in progress but a quick throw together.
Was gonna use a smile instead but not sure how that might be internationally. Not much better with english letters here but.

EDIT: What font is that brightghost? I like the i :smile:

**Comment by brightghost** [comment]
Consolas... was looking for something a little more angular but I think it works okay. I see now it's not quite visually centered...

**Comment by ygini** [comment]
@WardsParadox style with @brightghost font should be OK I think.

**Comment by WardsParadox** [comment]
![helloit](https://cloud.githubusercontent.com/assets/8117192/8840899/a370ef18-30a4-11e5-8690-11f0a49266be.png)

Combination as requested.
Below is sized at 22 px, which should work for the status bar icon.
https://cloud.githubusercontent.com/assets/8117192/8840971/89f6c6d8-30a5-11e5-9411-11625983480c.png

Let me know if you need anyother sizes.

**Comment by ygini** [comment]
@WardsParadox if you can, I need it in 16pt, 32pt, 128pt, 256pt, 512pt (in 1x and 2x for non-retina and retina). This will be for the application icon.

I also need a version for the status bar icon with special size and alignment. Look at the calculator at the end of this blog post: http://alastairs-place.net/blog/2013/07/23/nsstatusitem-what-size-should-your-icon-be/

**Comment by WardsParadox** [comment]
Will do. Once I'm on lunch, I'll render it out nice and quick. I'll send
the SVG if you would like as well.

Zack McCauley

**Comment by WardsParadox** [comment]
Properly Sized for status bar at 19x19
![statusbar](https://cloud.githubusercontent.com/assets/8117192/8882790/ef245748-3206-11e5-9dad-4b94493e2440.png)
I can render that out as an icns file for you if you like but here is an icon I built last night for the application, let me know if you like it.
![icon_256x256](https://cloud.githubusercontent.com/assets/8117192/8882809/4253eac8-3207-11e5-8993-57ac9b5227ad.png)

**Comment by ygini** [comment]
Perfect for me. 

The statusbar size is OK (but don't forget @2x, the same scale but 2 time bigger for retina display).

I need the previously listed size in independent file. Xcode prefer this to the old icns file.

**Comment by WardsParadox** [comment]
Let me know if this is what you need. All the sizes (including the @2x
options) and the status bar plus @2x for it as well.

EDIT: Whoops, Didn't attach the zip. Here's the link for that.
https://goo.gl/OmfSSZ
Zack

**Comment by ygini** [comment]
@WardsParadox thanks for your work. It has been integrated in the brand new GM pre-release.

You can see it here https://github.com/ygini/Hello-IT/releases/tag/v1.0-GM

If you've a retina display you will be able to see that the statusbar icon is a bit bigger than other apps.

You can try to fix it if you want by replacing the related image in the app bundle resources.

In two weeks from now, the GM will turn into first official release if nothing goes wrong.
