### ISSUE TITLE
imageBaseName doesn't work for script items

### ISSUE THREAD

**Issue by kevinmcox** [ygini/Hello-IT#60]
# Setup info

Hello-IT version: 1.5.0
macOS version: 10.15.7 (19H524)
Preferences deployed via: Configuration Profile
Preferences targeting: System

# Setup goal

Trying to use a static icon in front of script item: com.github.ygini.hello-it.hostname.sh

# Issue description

imageBaseName icons do not work for "public.script.item" or "public.test.http" items. They only appear to work for "public.open.application" and "public.open.resource" types.

# Requested solution

This lis low priority for me personally, but posting as requested on Slack. It would be nice to be able to specify an icon in front of script items that do not use a status color circle (like hostname, IP address, RAM, OS version, etc.)

# Notes

I also tested the following as well, but since these display state information with a colored circle it might be by design.:

com.github.ygini.hello-it.ip.sh
com.github.ygini.hello-it.public-ip.sh
com.github.wardsparadox.hello-it.computerdetails.uptime.sh
com.github.wardsparadox.hello-it.munki.pendingmscupdates.sh

**Comment by ygini** [comment]
Hello

I've spotted the issue here. This is because both `public.script.item` and `public.test.http` are functions with expected state. So when no state is known at this time, it return to a blank image.

I will update all state based items to return to `imageBaseName` when non state is known.

**Comment by ygini** [comment]
Solved in 1.6.0
