### ISSUE TITLE
Custom icons not following system theme

### ISSUE THREAD

**Issue by pfglobal** [ygini/Hello-IT#65]
# Setup info

Hello-IT version: 1.6.0
macOS version: 12.6.1
Preferences deployed via: Configuration Profile
Preferences targeting: user - device

# Setup goal

Follow other menu item styles in the menu bar

# Issue description

Hopefully self-explanatory with this screen recording!

https://user-images.githubusercontent.com/49640956/198251620-f0a0bd47-b1f1-475b-9fe6-793a907a3757.mp4

Seems to work fine with the default icons.

# Related logs

N/A

# Requested solution

Follow other menu item styles in the menu bar

# Notes

Any other comments you might find useful to add.

**Comment by ygini** [comment]
Will be fixed in 1.7.0
