### ISSUE TITLE
Won't execute on macOS 14 - 14.1.1

### ISSUE THREAD

**Issue by applebit924** [ygini/Hello-IT#68]
# Setup info

Hello-IT version: [Hello-IT v1.7.0 Beta 1]
macOS version: macOS 14.0, 14.1, 14.1.1
Preferences deployed via: Configuration Profile - MCX - defaults - dropped plist
Preferences targeting: user - device

# Setup goal

Menu Item should appear

# Issue description

Menu item does not appear.  Execute manually results in "Killed: exit 9"

# Related logs

-

# Requested solution

-

# Notes

-

**Comment by applebit924** [comment]
Appears to be Apple Silicon.  Intel not affected.

**Comment by ygini** [comment]
Do you have a crashlog please?

**Comment by applebit924** [comment]
I'll attempt to collect one.  This app is so useful in our org.

**Comment by applebit924** [comment]
A reinstall from the source and its fine.

**Comment by ygini** [comment]
Let me know if it happen again and I'm all in for beta feedback, so I can know if I can publish in release

**Comment by applebit924** [comment]
Awesome!

The revision was demo’d <https://docs.google.com/presentation/d/e/2PACX-1vS44F46yewgUuPxJMWu10Z8LabbA64Maj8HUzGnLQR9ogsV6szYqJ1CFq5Y6YjkD06jiAHZcIrFq-T2/pub?start=false&loop=false&delayms=3000&slide=id.g29b46f68b5e_0_0> today to all staff and then I had new laptops error.

- Jon McCullough

**Comment by ygini** [comment]
Excellent!!!

It’s not often that people share they use of the product, and since there is no telemetry for privacy reason, I have actually no idea how the solution is used!

Thanks!!
