### ISSUE TITLE
Is the purpose of public.test.http to test connection or verify contents?

### ISSUE THREAD

**Issue by brightghost** [ygini/Hello-IT#7]
Per https://github.com/ygini/Hello-IT/wiki/public.test.http :

> This function is used to check the content of a HTTP(S) web page. The aim of this function is to know if you can contact a server or not.
> 
> For example, you can add two instance of this function, one for checking access to Internet server and an other for Intranet servers.

It seems to me this is describing two cross purposes: checking _access_ to an http resource, and verifying the _contents_ of a resource. 

The first would be equivalent to a ping; I can accomplish this with a  public.script.item, though checking for HTTP response would be a welcome alternative method.

The second seems to be what this item actually does, with any of the three options; all are comparing the content of the resource to a known-good state. This obviously works with end-points specifically designed for this purpose such as the captive.apple.com in the example; it's less useful for testing other arbitrary pages with content that periodically changes. I can achieve this with the following:

```
 <key>mode</key>
 <string>contain</string>
 <key>originalString</key>
 <string>*</string>
```

but I think that's a bit non-obvious. Perhaps another mode for just this use-case could be included?

**Comment by ygini** [comment]
Indeed, this module is made to check the server answer. 

From my point of view it allow you to check the connection to the server by ensuring that the server is the real one.

Regarding the check done on the answer, you've multiple solution provided.

The main idea is to provide your own version of captive.apple.com, it's just a static html page in the end.

But you can use the contain mode to look only for a part of the page when the page is dynamic. Most of time headers and footers are static.

For example, in this own page, you kind find this:

```
<meta name="google-analytics" content="UA-3769691-2">
```

I bet it won't change every day.

**Comment by ygini** [comment]
Does this answer your question?

**Comment by brightghost** [comment]
It does, feel free to close this. I'm a bit nonplussed by the "test an arbitrary unlikely to change string" method because it seems prone to fail in non-obvious ways when testing a resource which is not under your own full control (which is certainly part of my use-case). Nonetheless the function is entirely usable for my purposes, with either your method, or my method above. 

If you're open to contributions to the documentation, I may elaborate a bit on this once I've had more time to explore the possibilities.

**Comment by ygini** [comment]
I'm 100% open to contribution of any kind, documentation and usecase included.

**Comment by erikng** [comment]
I would like to bring this up. It would be nice if you could just check if the URL is reachable vs what state it's in.

I need a very simple status for a URL that could change every 120 seconds.

**Comment by ygini** [comment]
@erikng on your web page, there is absolutely no constant string? Like an HTML identifier or something?

The main issue to not check the content is that you could be spoofed by a captive portal or something like that.

However, if your case don't need this check, you can already manage it with the current plugin.

Set the `mode` to `compare` and `originalString` to `dummy`, then set `unmatchingResult` to `HITPluginTestStateOK`.

This will set a check condition who will fail all the time but also tune the matching result to return a green state when the comparaison is false. So the only way to be not green will be not reachable (red) or no Internet (gray).

Does it cover your needs?

**Comment by erikng** [comment]
There are, but for example it might be a SAML redirect. I could look for SAML auth errors, but that seems kind of odd.

I think your example covers my need.

**Comment by ygini** [comment]
@erikng your case of SAML check might deserve a dedicated plugin instead of using one I already built.

No one created a custom plugin for now (or at least, no one told me). But I've created Hello IT to be extendable. You can write your own function in Objective-C (or Swift). PyObjC should work too but I've never used this.

Hello IT provide a HITDevKit with all base classes needed to handle all events coming from the main app. And you've all kind of plugin available here https://github.com/ygini/Hello-IT/tree/master/src/Plugins to understand how it work.

And the whole documentation is here https://github.com/ygini/Hello-IT/wiki/PluginCreation

If your case is advanced, that the best way to go. Way more powerful than the bash bridge I've made.

Using the plugin method, you can even run in background and catch real time events if you need to.

**Comment by erikng** [comment]
Thanks @ygini
