### ISSUE TITLE
Preference loading

### ISSUE THREAD

**Issue by phoopes** [ygini/Hello-IT#8]
This is a great little app that will come in VERY handy at our school. I'm testing it on my laptop (OS X Yosemite) and I'm having one small issue. I've created the plist preference file in ~/Library/Preferences and while it loaded the first time, I'm making changes and restarting but the app isn't loading the preference file again. It seems stuck on the first version I wrote. Is there a "reload" key that needs to be added or something else?

Thanks.

**Comment by ygini** [comment]
I think the problem isn't related to Hello-IT but to cfprefsd, the new preference caching process from Apple (or to be more honest, a new stupid arch linked to sandboxing who don't work really well).

Please, after editing your plist file manually, can you issue a killall cfprefsd in your terminal ? With your user rights, no need to be root for that.

**Comment by phoopes** [comment]
ygini/Hello-IT
reply@reply.github.com
on September 4, 2015 at 1:52 AM -0400 wrote:

> I think the problem isn't related to Hello-IT but to cfprefsd, the new
> preference caching process from Apple (or to be more honest, a new stupid
> arch linked to sandboxing who don't work really well).
> 
> Please, after editing your plist file manually, can you issue a killall
> cfprefsd in your terminal ? With your user rights, no need to be root for
> that.

You are exactly right. I found that after I sent the email and that does
work. It's a pain for testing purposes but at least I know now what's
going on.

I appreciate your response. Thanks!

# 

Peter Hoopes
Director of Information Services
St. Andrew's School

# phoopes@standrews-de.org
